version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
    commit-message: { prefix: "ci" }
    labels: [dependencies, ci]
  - package-ecosystem: swift
    directory: /app
    schedule: { interval: monthly }
    commit-message: { prefix: "build", include: scope }
    labels: [dependencies, app]
